server {
  listen 80;
  root /var/www/nexusphere/public;
  error_log /var/log/nginx/error.log warn;
  index index.php index.html;
  client_max_body_size 600M;
  client_body_timeout 600;
  client_header_timeout 600;

  # location /は先頭が/で始まるURIで一致。(全リクエストに一致)  
  # try_filesは以降に指定した順番に存在をチェックし、存在すればそれが処理される
  # http://localhost:8000/index.php なら、 index.phpを返す
  # ファイルが無かったら、次に$uri/なので、index.php/を探して、そこのファイルを返す
  # それでもなければ、index.phpを無条件で返す
  location / {
    try_files $uri $uri/ /index.php?$query_string;
    fastcgi_read_timeout 600;
  }

  #  基本的に location / の結果としてindex.phpになって内部リダイレクトされている前提。
  #  index.phpで内部リダイレクトされるので、location ~ \.php$ にマッチ。
  #  あとは、location ~ \.php$の設定に従い、php-fpmを経由してLaravelの開始スクリプトのindex.phpが実行される。  
  location ~ \.php$ {
    try_files $uri =404;
    fastcgi_split_path_info ^(.+\.php)(/.+)$;
    # php-fpmが起動しているサーバーのIPとポート番号
    fastcgi_pass app-nexus:9000; 
    fastcgi_index index.php;
    include fastcgi_params;
    # /var/www/documentroot/public/ + fastcgi_script_name(URLのドメイン以降のパスが入る)
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_param PATH_INFO $fastcgi_path_info;
  }
 }
server {
    listen 80;
    server_name dev.nexusphere.top;
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name dev.nexusphere.top;
    root /var/www/nexusphere-dev/nexusphere/public;
    ssl_certificate /etc/letsencrypt/live/dev.nexusphere.top/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/dev.nexusphere.top/privkey.pem;
    index index.php index.html;
    client_max_body_size 600M;
    client_body_timeout 600;
    client_header_timeout 600;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }
    location / {
        try_files $uri $uri/ /index.php?$query_string;
        fastcgi_read_timeout 600;
    }
    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass app-nexus-dev:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
}
